<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-04-13 09:29

$extensionPath = t3lib_extMgm::extPath('loginprotection');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'tx_loginprotection_hooks_bootstrapexttablesinclusionpostprocessing' => $extensionClassesPath . 'Hooks/BootstrapExtTablesInclusionPostProcessing.php',
	'tx_loginprotection_hooks_indexloginformhook' => $extensionClassesPath . 'Hooks/IndexLoginFormHook.php',
	'tx_loginprotection_hooks_t3libuserauthpostuserlookuphook' => $extensionClassesPath . 'Hooks/T3libUserauthPostUserLookUpHook.php',
);
?>